### PR TITLE
changed env key input in deploy

### PR DESCRIPTION
**Pull request by joshisacow**

### CODE REVIEW

**Comment by joshisacow** [comment]
Could be: build_env_vars: (Optional) List of key=value pairs to set as environment variables during tbe build process. This will overwrite any duplicate key environment variables defined in the app.yaml.

**Comment by joshisacow** [comment]
Is there a way to test push tests without actually pushing or changing the .yml files

**Comment by joshisacow** [comment]
> Is there a way to test push tests without actually pushing or changing the .yml files

seems like I need to add 'on: workflow_dispatch' to the files, ill check it tmr.

**Comment by haiyangc** [comment]
> Is there a way to test push tests without actually pushing or changing the .yml files

Just go to the actions tab and click run

**Review by haiyangc — APPROVED** [review]

**Pull request merged**
